fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    efi: "https://github.com/jcpunk/puppet-efi.git"
    augeasproviders_grub: "https://github.com/hercules-team/augeasproviders_grub.git"
    provision: "https://github.com/puppetlabs/provision.git"
  symlinks:
    grub2: "#{source_dir}"
